### ISSUE TITLE
consider using a phpbench/phpbench for benchmarking

### ISSUE THREAD

**Issue by Ocramius** [kocsismate/php-di-container-benchmarks#4] opened 2017-01-07 00:37 UTC
Just a suggestion, but phpbench generally also deals with things like standard deviation and reporting (as well as saving reports)

**Comment by kocsismate** [comment] 2017-01-07 00:44
Thank you for the suggestion! I have already considered using it, but for the first sight it seemed to me that its configuration didn't match what I wanted. I'll definitiely look at it again soon (at least for some suggestions how to measure the results better).

**Comment by Ocramius** [comment] 2017-01-07 00:48
You can look at https://github.com/Roave/FunctionFQNReplacer for examples.
There are also before and after execution hooks. The number of iterations
and revolutions is generally passed via cli parameters.

**Comment by theofidry** [comment] 2017-01-07 09:53
@kocsismate another advantage is that you won't have to pass via an `exec` and as a result be able to profile it know where the diff comes from from a container to another

**Comment by dunglas** [comment] 2017-01-07 09:54
@theofidry you can already do profile `/code/bin/test` directly. But phpbench will indeed be a good move.

**Comment by kocsismate** [comment] 2017-01-07 11:11
OK, I am started to think through how I could use PHPBench efficiently. I'd like to get your feedback about my idea:

Instead of executing `/code/bin/test`, I could execute phpbench instead like this:

```bash
phpbench run /path/to/container/Test{{ $number }}.php --iterations={{ $iterations }} --revs={{ $runs }} --warmup=1 --retry-threshold=5 --bootstrap=/code/app/bootstrap.php
```
Maybe I could dump the results to an XML file or create a custom report generator which outputs the result as JSON to `stdout` so I could gather the results (+ other metrics of of the measurement itself) as before.

What do you think about this idea?

**Comment by Ocramius** [comment] 2017-01-07 14:24
Why would you specify the container in the run command? One command to test
them all ;-)

**Comment by kocsismate** [comment] 2017-01-07 15:46
Fair point :)

**Comment by sagikazarmark** [comment] 2017-01-07 15:59
> I could execute phpbench like this

There is a configuration file which would allow to avoid passing every parameter to the command

> phpbench run /path/to/container/Test{{ $number }}.php

I would rather give the tests some name instead of numbers

> create a custom report generator

Why not an HTML generator which generates the existing format?

This startup time thing seems to be a little bit vague to me, especially because in many cases the excluded version contains a higher number. I guess this is partly because of the tests are not that stable, but could also mean that it is negligible and you shouldn't really care about it. If you really want to represent this time, you could write a separate benchmark for it, but even then this negligible portion might not even be visible, so it could give you false results.

**Comment by sagikazarmark** [comment] 2017-01-07 16:01
Hm, looking at the current benchmark results, I might be wrong about my previous assumptions. Especially Disco seems to perform pretty badly on this front.

**Comment by kocsismate** [comment] 2017-01-07 16:15
Look at the newly generated results without docker for mac! Disco boosted
up! I guess filesystem speed can be the reason. I wont be available for
some hours to inspect it.

2017. jan. 7. du. 5:02 ezt írta ("Márk Sági-Kazár" <notifications@github.com

**Comment by Ocramius** [comment] 2017-01-07 16:23
Fileystem is only involved at container generation - that's build-time, not
runtime.

Marco Pivetta

http://twitter.com/Ocramius

http://ocramius.github.com/

**Comment by kocsismate** [comment] 2017-01-08 02:29
No, I thought that Disco does something crazy with the filesystem in run-time but that was just a silly idea I shouldn't have mentioned.

Anyway, as suggested in https://github.com/kocsismate/php-di-container-benchmarks/issues/11 I plan to also include autoload time when container startup time is measured. This will mean quite a big change in the results. Please let me know if you have any objections.

**Comment by Ocramius** [comment] 2017-01-08 02:47
Autoload, build/compile/etc could be *added* to the matrix, but that's exactly what the warmup allows to detect and remove from the execution, since all what matters is the actual runtime retrieval/instantiation of services.

**Comment by TomBZombie** [comment] 2017-01-08 17:18
Not really. In a production environment you'd connect to a web server, the server launches the php script, the container is created/configured, some objects are retrieved and the process finishes. This is actually a more meaningful test, if a container can return a service in 0.001s that's great, but if it takes 1s of warmup time due to autoloading dozens of files and parsing config files its actually slower in the real world than a container that takes 0.002s to retrieve an instance but has a 0.1s warmup time. At some number of objects per request, that additional startup time won't matter. I'd be interested in that number, and the number of objects which are retrieved from the container in various frameworks

**Comment by Ocramius** [comment] 2017-01-08 17:20
@TomBZombie agreed, but the `get()` and `create()` (or whatever) calls will be repeated (`O(n)`), whereas the instantiation is a `O(1)`. Separated benchmarks are needed :-)

**Comment by TomBZombie** [comment] 2017-01-08 17:40
The problem caused by that is as `n`  is increased the effect of instantiation is reduced. We need a sane (or variable) value for n. 

Consider the numbers I suggested above. If you add warmup time and n*get() calls, if n is high enough the warmup time becomes irrelevant (it's warmup time/n) because it becomes part of the average. As I suggested in #11 the entire php process from startup to exit needs to be benchmarked (with various values for n)

**Comment by kocsismate** [comment] 2017-01-08 17:44
When I measured the results including autoload time, the order of the containers changed a lot (e.g. Symfony went into the mid-range for tasks where iteration time is 10, it became 3rd when iteration is 100 and only went to the top when it was 1000 in the first tests suite).

And I'm might not be true, but I see that autoloading takes an order of magnitude longer than the main task in some tests so I can also agree with Tom that autoloading _can_ impact the total time consumption significantly. In my apps I don't use the container more than 10-15 times, so at least for me at least it can be useful to include autoloading in the measurements.

But we discussed with @sagikazarmark that opcache can improve autoloading and although I can easily enable it in Docker it can't help much because the process exists after each tests. So what I see is that we can't really simulate a "production-alike" autoloading that's why bulkier containers get a handicap which they wouldn't with proper opcache in a web server. Please correct me if I am wrong.

**Comment by TomBZombie** [comment] 2017-01-08 17:50
I don't know much about docker but that's what happens on most webservers (nginx, fastcgi, the only exception is mod_php and I don't think it improves the opcache), the php process exits after the request is complete and is launched again on the next request. The opcache is still used by the next process as far as I'm aware

**Comment by kocsismate** [comment] 2017-01-08 17:54
First I only read the accepted answer from this SO question (http://stackoverflow.com/questions/25044817/zend-opcache-opcache-enable-cli-1-or-0-what-does-it-do) but I've just discovered in another answer that in PHP 7 the situation changed. I'll look try to see if it improves peformance.

**Comment by TomBZombie** [comment] 2017-01-08 17:56
Also,  xdebug really screws with the results so make sure it's not enabled when you run the benchmarks. When I was testing it, pimple was about twice as slow as dice with xdebug enabled, with it turned off they we're practically identical.

**Comment by Ocramius** [comment] 2017-01-08 17:58
@TomBZombie 

 > The problem caused by that is as `n` is increased the effect of instantiation is reduced. We need a sane (or variable) value for n.

 * Bootstrap bench uses one bootstrap + one instantiation
 * Instantiation bench uses a huge amount of instantiations, and excludes bootstrap
 * Fetch bench uses a huge amount of fetches, and excludes bootstrap and instantiation

Clear?

As for docker, make sure all files are pre-loaded into an existing opcache during the `docker build` command, or at least do that autoloading as entrypoint, before actually running any benchmarks. Enabling on CLI is needed, and the bench should be run with `php -n` (for XDebug). In general, you should not see any `file_exists()` or `is_readable()` calls at runtime when profiling.

**Comment by TomBZombie** [comment] 2017-01-08 18:19
That sounds good, I'd also like to see the bootstrap bench with 1, 10, 50, 100, 250, 500, 1000 instantiations. We should see some nice races there where some containers will win at lower objects but be overtaken by other containers as the number of objects is increased. It would be interesting to chart them and see wgere the lines intersect.

**Comment by Ocramius** [comment] 2017-01-08 18:24
> I'd also like to see the bootstrap bench with 1, 10, 50, 100, 250, 500, 1000 instantiations.

That's something that phpbench already has OOTB ;-)

**Comment by kocsismate** [comment] 2017-01-08 18:31
Yeah, this sounds a nice common ground :) I'll try to implement the 3 types of tests, but first let me work on improving stability of the tests. :) Hopefully with PHPBench!

P.S:  I had a really shameful bug in the test runner which I've just fixed in this commit: https://github.com/kocsismate/php-di-container-benchmarks/commit/441159b8e73f6ff8d4774eddae7e3ee845b2b32a#diff-e4c978e35c4068319fb25cba74156bf1R64

`exec` passes the `$output` by reference but this variable wasn't declared before, so somehow it always got the same value in each iteration... I've never met something like this before. :S After the fix the tests are more stable, but I'll move to phpbench to improve it ever further.

**Comment by kocsismate** [comment] 2017-01-17 23:41
I tried to integrate phpbench into my benchmark but after quite a bit of thinking I realized that maintability of tests would probably be harmed if I did it.

The problem I saw is that there are currently 18 test variations (6 test suite x 3 test cases) and it only takes 12 lines per container to be able to run all of them, but with phpbench it seemed that it would take many more lines to achieve this. Maybe I am missing something and there is a way to integrate phpbench without rewriting all the tests, but I believe the solution wouldn't be as clear and easy to follow as it is now.

Apart from this, the good news is that I managed to make the tests much more stable (time differences between two runs are usually less than 0,01 ms for the same containers), furthermore I implemented the 3 types of measurements we talked about, and tests are now run via PHP-FPM with Opcache enabled in order to better simulate a production environment.

On the flip side, running the benchmark in Docker (at least via my Docker for Mac) produces very unreliable results so I had to setup the stack on my host machine. :/

I am closing this issue because I believe the benchmark reached its purpose; maybe its precision is not the best, but I believe it is good enough now. So thank you all for the great input, I appreciate it very much! :)

**Closed by kocsismate** 2017-01-17 23:41 UTC
